### PR TITLE
l1 improvements for meow script

### PR DESCRIPTION
**Pull request by crystaltype**
@vv-monsalve 
Screen Shot 2021-10-12 at 13 33 31
Screen Shot 2021-10-12 at 13 33 48
Screen Shot 2021-10-12 at 13 34 09
Screen Shot 2021-10-12 at 13 34 27
Screen Shot 2021-10-12 at 13 34 55
Screen Shot 2021-10-12 at 13 35 28
Screen Shot 2021-10-12 at 13 35 52

### CODE REVIEW

**Comment by crystaltype** [comment]
@vv-monsalve I've inspected the cl actions but I have no idea why it's giving me error, something's related to strokeshortcomb.titl. I've seen the font has a set of titl diacritics, but from what I've seen, it isn't necessary to keep them so I t deleted them.

**Comment by crystaltype** [comment]
@vv-monsalve I finally resolved the error, I think it's ready now. The only FAIL in the action is because of the VM :)

**Comment by vv-monsalve** [comment]
> @vv-monsalve I finally resolved the error, I think it's ready now. The only FAIL in the action is because of the VM :)

Happy to hear this :)
What was the issue? Was it related to `strokeshortcomb.titl` missed as a component in a compound glyph at the end?

**Comment by crystaltype** [comment]
> > @vv-monsalve I finally resolved the error, I think it's ready now. The only FAIL in the action is because of the VM :)
> 
> Happy to hear this :) What was the issue? Was it related to `strokeshortcomb.titl` missed as a component in a compound glyph at the end?

Yes, turns out Lslash.titl is using it as a component, I used the "Find and Replace component" in Mekkablue's script to find which was the culprit :)

**Pull request merged**
